[2022-07-24 19:12:30,689] {processor.py:153} INFO - Started process (PID=77227) to work on /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:12:30,689] {processor.py:641} INFO - Processing file /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-07-24 19:12:30,689] {logging_mixin.py:115} INFO - [2022-07-24 19:12:30,689] {dagbag.py:507} INFO - Filling up the DagBag from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:12:30,702] {logging_mixin.py:115} INFO - [2022-07-24 19:12:30,702] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-07-24 19:12:30,702] {logging_mixin.py:115} INFO - [2022-07-24 19:12:30,702] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-07-24 19:12:30,702] {processor.py:653} WARNING - No viable dags retrieved from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:12:30,729] {processor.py:161} INFO - Processing /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2022-07-24 19:13:01,769] {processor.py:153} INFO - Started process (PID=77336) to work on /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:13:01,769] {processor.py:641} INFO - Processing file /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-07-24 19:13:01,769] {logging_mixin.py:115} INFO - [2022-07-24 19:13:01,769] {dagbag.py:507} INFO - Filling up the DagBag from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:13:01,783] {logging_mixin.py:115} INFO - [2022-07-24 19:13:01,783] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-07-24 19:13:01,783] {logging_mixin.py:115} INFO - [2022-07-24 19:13:01,783] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-07-24 19:13:01,783] {processor.py:653} WARNING - No viable dags retrieved from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:13:01,813] {processor.py:161} INFO - Processing /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2022-07-24 19:13:32,858] {processor.py:153} INFO - Started process (PID=77446) to work on /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:13:32,858] {processor.py:641} INFO - Processing file /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-07-24 19:13:32,858] {logging_mixin.py:115} INFO - [2022-07-24 19:13:32,858] {dagbag.py:507} INFO - Filling up the DagBag from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:13:32,870] {logging_mixin.py:115} INFO - [2022-07-24 19:13:32,870] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-07-24 19:13:32,870] {logging_mixin.py:115} INFO - [2022-07-24 19:13:32,870] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-07-24 19:13:32,870] {processor.py:653} WARNING - No viable dags retrieved from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:13:32,902] {processor.py:161} INFO - Processing /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2022-07-24 19:14:03,641] {processor.py:153} INFO - Started process (PID=77596) to work on /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:14:03,641] {processor.py:641} INFO - Processing file /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-07-24 19:14:03,641] {logging_mixin.py:115} INFO - [2022-07-24 19:14:03,641] {dagbag.py:507} INFO - Filling up the DagBag from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:14:03,653] {logging_mixin.py:115} INFO - [2022-07-24 19:14:03,653] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-07-24 19:14:03,653] {logging_mixin.py:115} INFO - [2022-07-24 19:14:03,653] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-07-24 19:14:03,653] {processor.py:653} WARNING - No viable dags retrieved from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:14:03,685] {processor.py:161} INFO - Processing /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2022-07-24 19:14:34,787] {processor.py:153} INFO - Started process (PID=77705) to work on /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:14:34,788] {processor.py:641} INFO - Processing file /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-07-24 19:14:34,788] {logging_mixin.py:115} INFO - [2022-07-24 19:14:34,788] {dagbag.py:507} INFO - Filling up the DagBag from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:14:34,800] {logging_mixin.py:115} INFO - [2022-07-24 19:14:34,800] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-07-24 19:14:34,800] {logging_mixin.py:115} INFO - [2022-07-24 19:14:34,800] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-07-24 19:14:34,800] {processor.py:653} WARNING - No viable dags retrieved from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:14:34,830] {processor.py:161} INFO - Processing /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2022-07-24 19:15:06,079] {processor.py:153} INFO - Started process (PID=77825) to work on /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:15:06,080] {processor.py:641} INFO - Processing file /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-07-24 19:15:06,080] {logging_mixin.py:115} INFO - [2022-07-24 19:15:06,080] {dagbag.py:507} INFO - Filling up the DagBag from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:15:06,093] {logging_mixin.py:115} INFO - [2022-07-24 19:15:06,093] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-07-24 19:15:06,093] {logging_mixin.py:115} INFO - [2022-07-24 19:15:06,093] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-07-24 19:15:06,093] {processor.py:653} WARNING - No viable dags retrieved from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:15:06,122] {processor.py:161} INFO - Processing /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2022-07-24 19:15:36,888] {processor.py:153} INFO - Started process (PID=77931) to work on /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:15:36,888] {processor.py:641} INFO - Processing file /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-07-24 19:15:36,888] {logging_mixin.py:115} INFO - [2022-07-24 19:15:36,888] {dagbag.py:507} INFO - Filling up the DagBag from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:15:36,900] {logging_mixin.py:115} INFO - [2022-07-24 19:15:36,900] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-07-24 19:15:36,900] {logging_mixin.py:115} INFO - [2022-07-24 19:15:36,900] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-07-24 19:15:36,901] {processor.py:653} WARNING - No viable dags retrieved from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:15:36,929] {processor.py:161} INFO - Processing /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2022-07-24 19:16:08,159] {processor.py:153} INFO - Started process (PID=78036) to work on /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:16:08,159] {processor.py:641} INFO - Processing file /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-07-24 19:16:08,160] {logging_mixin.py:115} INFO - [2022-07-24 19:16:08,160] {dagbag.py:507} INFO - Filling up the DagBag from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:16:08,172] {logging_mixin.py:115} INFO - [2022-07-24 19:16:08,172] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-07-24 19:16:08,172] {logging_mixin.py:115} INFO - [2022-07-24 19:16:08,172] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-07-24 19:16:08,172] {processor.py:653} WARNING - No viable dags retrieved from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:16:08,202] {processor.py:161} INFO - Processing /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2022-07-24 19:16:40,250] {processor.py:153} INFO - Started process (PID=78149) to work on /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:16:40,250] {processor.py:641} INFO - Processing file /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-07-24 19:16:40,251] {logging_mixin.py:115} INFO - [2022-07-24 19:16:40,251] {dagbag.py:507} INFO - Filling up the DagBag from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:16:40,263] {logging_mixin.py:115} INFO - [2022-07-24 19:16:40,263] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-07-24 19:16:40,263] {logging_mixin.py:115} INFO - [2022-07-24 19:16:40,263] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-07-24 19:16:40,263] {processor.py:653} WARNING - No viable dags retrieved from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:16:40,292] {processor.py:161} INFO - Processing /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2022-07-24 19:17:11,937] {processor.py:153} INFO - Started process (PID=78256) to work on /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:17:11,938] {processor.py:641} INFO - Processing file /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-07-24 19:17:11,938] {logging_mixin.py:115} INFO - [2022-07-24 19:17:11,938] {dagbag.py:507} INFO - Filling up the DagBag from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:17:11,950] {logging_mixin.py:115} INFO - [2022-07-24 19:17:11,950] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-07-24 19:17:11,950] {logging_mixin.py:115} INFO - [2022-07-24 19:17:11,950] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-07-24 19:17:11,950] {processor.py:653} WARNING - No viable dags retrieved from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:17:11,980] {processor.py:161} INFO - Processing /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2022-07-24 19:17:44,926] {processor.py:153} INFO - Started process (PID=78627) to work on /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:17:44,926] {processor.py:641} INFO - Processing file /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-07-24 19:17:44,926] {logging_mixin.py:115} INFO - [2022-07-24 19:17:44,926] {dagbag.py:507} INFO - Filling up the DagBag from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:17:44,955] {logging_mixin.py:115} INFO - [2022-07-24 19:17:44,955] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-07-24 19:17:44,955] {logging_mixin.py:115} INFO - [2022-07-24 19:17:44,955] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-07-24 19:17:44,956] {processor.py:653} WARNING - No viable dags retrieved from /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-07-24 19:17:45,004] {processor.py:161} INFO - Processing /Users/jangheesu/opt/anaconda3/envs/airflow2.3.0/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.079 seconds
